[package]
name = "chauve"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.15.19"
serde = { version = "1.0.228", features = ["derive"] }
chrono = { version = "0.4.42", features = ["serde"] }
dioxus = { version = "0.7.1", features = [] }
reqwest = { version = "0.12.24", features = ["json"] }
tokio = {version="1.48.0", features = ["macros","time"]}
async-trait = "0.1.89"
dioxus-free-icons = { version = "0.10", features = ["font-awesome-brands","font-awesome-solid"] }
futures = "0.3"
anyhow = "1.0.102"
thiserror = "2.0.18"
tracing = "0.1.44"
dioxus-logger = "0.7.4"
toml = "1.1.2"
directories = "5"
[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
